# Site settings
title: "Lyubomir Hristov"
email: lyubomir.hristov3@gmail.com
description: "Personal blog"
url: "http://lubomirhristov.github.io"
baseurl: "/blog"
title_description: "Second year Software Engineering student at the University of Southampton skilled in programming and problem solving. I am a highly motivated and passionate young person with a lot of potential and abilities, showing great interest in software development and open to learning new things. I am a very enthusiastic and keen programmer."
title_image: "favicons/me.jpg"


# Social usernames/URLs
github_username:  LubomirHristov
linkedin_link: https://www.linkedin.com/in/lyubomir-hristov-51b498151/

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
